apiVersion: apps/v1 
kind: Deployment
metadata:
  name: crate-adapter-deployment
spec:
  selector:
    matchLabels:
      app: crate-adapter
  replicas: 3
  template:
    metadata:
      labels:
        app: crate-adapter
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: crate-adapter
        image: prometheus:crate-adapter
        imagePullPolicy: Always
        ports:
        - containerPort: 9268
          name: crate-adapter
