kind: Service
apiVersion: v1
metadata:
  name: nodeport-service
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    protocol: TCP
    name: prometheus-web
  selector:
    app: prometheus
